version: "3.6"
services:
  #=== 網頁伺服器的container ======================
  web:
    image: jerry/php53-apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./projects:/var/www/html
      - ./etc/php:/usr/local/etc/php/conf.d
      - ./log/web:/var/log/apache2
      - ./etc/default.conf:/etc/apache2/sites-enabled/default.conf
      - ./etc/ssl:/etc/apache2/ssl
    hostname: web
    networks:
      - net

  #=== 資料庫 container ===========================
  db:
    image: mysql:5.7.19
    hostname: db
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
      - ./data:/var/lib/mysql
    environment:
      #- MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD-secret}
      - MYSQL_ALLOW_EMPTY_PASSWORD= "yes"
      - TZ=Asia/Taipei
    networks:
      - net

######top-level netowks key#######
networks:
  net:
